2018-04-21 15:12:53,265 - main_server - ERROR - ***
2018-04-21 15:12:53,266 - main_server - ERROR - ERROR OCCURRED WHILE KICKING CHILDREN
2018-04-21 15:12:53,266 - main_server - ERROR - Node id: 2 was kicking child 4 from childList
2018-04-21 15:12:53,266 - main_server - ERROR - Traceback (most recent call last):
  File "/Users/vimanyuaggarwal/Python Projects/cmpe294A/code/phase1/main_server.py", line 99, in Size
    db.spanningtree.update_one({'nodeId': self.node.id}, {'$set': {'childListId': self.node.childList,
AttributeError: Node instance has no attribute 'childList'

2018-04-21 15:12:53,266 - main_server - ERROR - ***
2018-04-21 15:12:53,271 - main_server - ERROR - ***
2018-04-21 15:12:53,271 - main_server - ERROR - ERROR OCCURRED WHILE KICKING CHILDREN
2018-04-21 15:12:53,272 - main_server - ERROR - Node id: 0 was kicking child 2 from childList
2018-04-21 15:12:53,272 - main_server - ERROR - Traceback (most recent call last):
  File "/Users/vimanyuaggarwal/Python Projects/cmpe294A/code/phase1/main_server.py", line 99, in Size
    db.spanningtree.update_one({'nodeId': self.node.id}, {'$set': {'childListId': self.node.childList,
AttributeError: Node instance has no attribute 'childList'

2018-04-21 15:12:53,273 - main_server - ERROR - ***
2018-04-21 15:12:55,270 - main_server - ERROR - ***
2018-04-21 15:12:55,271 - main_server - ERROR - ERROR OCCURRED WHILE KICKING CHILDREN
2018-04-21 15:12:55,271 - main_server - ERROR - Node id: 7 was kicking child 8 from childList
2018-04-21 15:12:55,271 - main_server - ERROR - Traceback (most recent call last):
  File "/Users/vimanyuaggarwal/Python Projects/cmpe294A/code/phase1/main_server.py", line 98, in Size
    self.node.childListId.remove(request.nodeId)
ValueError: list.remove(x): x not in list

2018-04-21 15:12:55,271 - main_server - ERROR - ***
2018-04-21 15:12:57,276 - main_server - ERROR - ***
2018-04-21 15:12:57,276 - main_server - ERROR - ERROR OCCURRED WHILE KICKING CHILDREN
2018-04-21 15:12:57,276 - main_server - ERROR - Node id: 0 was kicking child 1 from childList
2018-04-21 15:12:57,276 - main_server - ERROR - Traceback (most recent call last):
  File "/Users/vimanyuaggarwal/Python Projects/cmpe294A/code/phase1/main_server.py", line 99, in Size
    db.spanningtree.update_one({'nodeId': self.node.id}, {'$set': {'childListId': self.node.childList,
AttributeError: Node instance has no attribute 'childList'

2018-04-21 15:12:57,277 - main_server - ERROR - ***
