2018-05-04 17:27:59,748 - Node - ERROR - ***Expected Error Ignore ***
2018-05-04 17:27:59,748 - Node - ERROR - 'NoneType' object is not iterable
2018-05-04 17:27:59,748 - Node - ERROR - Traceback (most recent call last):
  File "/Users/vimanyuaggarwal/Python Projects/cmpe294A/code/phase1/Node.py", line 349, in checkEnergy
    for child in node['childListId']:
TypeError: 'NoneType' object is not iterable

2018-05-04 17:27:59,748 - Node - ERROR - ***Expected Error Ignore ***
2018-05-04 17:27:59,749 - Node - ERROR - ***Expected Error Ignore ***
2018-05-04 17:27:59,749 - Node - ERROR - 'NoneType' object is not iterable
2018-05-04 17:27:59,749 - Node - ERROR - Traceback (most recent call last):
  File "/Users/vimanyuaggarwal/Python Projects/cmpe294A/code/phase1/Node.py", line 369, in checkEnergy
    for child in node['childListId']:
TypeError: 'NoneType' object is not iterable

2018-05-04 17:27:59,749 - Node - ERROR - ***Expected Error Ignore ***
2018-05-04 17:28:27,884 - Node - ERROR - ***Expected Error Ignore ***
2018-05-04 17:28:27,884 - Node - ERROR - 'NoneType' object is not iterable
2018-05-04 17:28:27,884 - Node - ERROR - Traceback (most recent call last):
  File "/Users/vimanyuaggarwal/Python Projects/cmpe294A/code/phase1/Node.py", line 349, in checkEnergy
    for child in node['childListId']:
TypeError: 'NoneType' object is not iterable

2018-05-04 17:28:27,884 - Node - ERROR - ***Expected Error Ignore ***
2018-05-04 17:28:27,885 - Node - ERROR - ***Expected Error Ignore ***
2018-05-04 17:28:27,885 - Node - ERROR - 'NoneType' object is not iterable
2018-05-04 17:28:27,885 - Node - ERROR - Traceback (most recent call last):
  File "/Users/vimanyuaggarwal/Python Projects/cmpe294A/code/phase1/Node.py", line 369, in checkEnergy
    for child in node['childListId']:
TypeError: 'NoneType' object is not iterable

2018-05-04 17:28:27,885 - Node - ERROR - ***Expected Error Ignore ***
2018-05-04 17:40:56,258 - Node - ERROR - ***Expected Error Ignore ***
2018-05-04 17:40:56,258 - Node - ERROR - 'NoneType' object is not iterable
2018-05-04 17:40:56,259 - Node - ERROR - Traceback (most recent call last):
  File "/Users/vimanyuaggarwal/Python Projects/cmpe294A/code/phase1/Node.py", line 349, in checkEnergy
    for child in node['childListId']:
TypeError: 'NoneType' object is not iterable

2018-05-04 17:40:56,259 - Node - ERROR - ***Expected Error Ignore ***
2018-05-04 17:40:56,259 - Node - ERROR - ***Expected Error Ignore ***
2018-05-04 17:40:56,260 - Node - ERROR - 'NoneType' object is not iterable
2018-05-04 17:40:56,260 - Node - ERROR - Traceback (most recent call last):
  File "/Users/vimanyuaggarwal/Python Projects/cmpe294A/code/phase1/Node.py", line 369, in checkEnergy
    for child in node['childListId']:
TypeError: 'NoneType' object is not iterable

2018-05-04 17:40:56,260 - Node - ERROR - ***Expected Error Ignore ***
2018-05-04 18:26:12,086 - client - ERROR - Node:1 - <_Rendezvous of RPC that terminated with (StatusCode.UNAVAILABLE, Connect Failed)>
2018-05-04 18:26:12,088 - client - ERROR - Traceback (most recent call last):
  File "/Users/vimanyuaggarwal/Python Projects/cmpe294A/code/phase1/client.py", line 413, in sendHello
    senderState=nodeState,senderClusterheadId=nodeClusterheadId))
  File "/Users/vimanyuaggarwal/anaconda/envs/env-iNet/lib/python2.7/site-packages/grpc/_channel.py", line 492, in __call__
    return _end_unary_response_blocking(state, call, False, deadline)
  File "/Users/vimanyuaggarwal/anaconda/envs/env-iNet/lib/python2.7/site-packages/grpc/_channel.py", line 440, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
_Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.UNAVAILABLE, Connect Failed)>

2018-05-04 18:26:32,089 - client - ERROR - Node:0 - <_Rendezvous of RPC that terminated with (StatusCode.UNAVAILABLE, Connect Failed)>
2018-05-04 18:26:32,089 - client - ERROR - Traceback (most recent call last):
  File "/Users/vimanyuaggarwal/Python Projects/cmpe294A/code/phase1/client.py", line 413, in sendHello
    senderState=nodeState,senderClusterheadId=nodeClusterheadId))
  File "/Users/vimanyuaggarwal/anaconda/envs/env-iNet/lib/python2.7/site-packages/grpc/_channel.py", line 492, in __call__
    return _end_unary_response_blocking(state, call, False, deadline)
  File "/Users/vimanyuaggarwal/anaconda/envs/env-iNet/lib/python2.7/site-packages/grpc/_channel.py", line 440, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
_Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.UNAVAILABLE, Connect Failed)>

2018-05-04 18:56:20,801 - client - ERROR - Node:11 - <_Rendezvous of RPC that terminated with (StatusCode.UNAVAILABLE, Connect Failed)>
2018-05-04 18:56:20,802 - client - ERROR - Traceback (most recent call last):
  File "/Users/vimanyuaggarwal/Python Projects/cmpe294A/code/phase1/client.py", line 415, in sendHello
    senderState=nodeState,senderClusterheadId=nodeClusterheadId))
  File "/Users/vimanyuaggarwal/anaconda/envs/env-iNet/lib/python2.7/site-packages/grpc/_channel.py", line 492, in __call__
    return _end_unary_response_blocking(state, call, False, deadline)
  File "/Users/vimanyuaggarwal/anaconda/envs/env-iNet/lib/python2.7/site-packages/grpc/_channel.py", line 440, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
_Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.UNAVAILABLE, Connect Failed)>

2018-05-04 18:57:50,065 - client - ERROR - Node:11 - <_Rendezvous of RPC that terminated with (StatusCode.UNAVAILABLE, Connect Failed)>
2018-05-04 18:57:50,066 - client - ERROR - Traceback (most recent call last):
  File "/Users/vimanyuaggarwal/Python Projects/cmpe294A/code/phase1/client.py", line 415, in sendHello
    senderState=nodeState,senderClusterheadId=nodeClusterheadId))
  File "/Users/vimanyuaggarwal/anaconda/envs/env-iNet/lib/python2.7/site-packages/grpc/_channel.py", line 492, in __call__
    return _end_unary_response_blocking(state, call, False, deadline)
  File "/Users/vimanyuaggarwal/anaconda/envs/env-iNet/lib/python2.7/site-packages/grpc/_channel.py", line 440, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
_Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.UNAVAILABLE, Connect Failed)>

2018-05-04 18:58:26,768 - client - ERROR - Node:11 - <_Rendezvous of RPC that terminated with (StatusCode.UNAVAILABLE, Connect Failed)>
2018-05-04 18:58:26,769 - client - ERROR - Traceback (most recent call last):
  File "/Users/vimanyuaggarwal/Python Projects/cmpe294A/code/phase1/client.py", line 415, in sendHello
    senderState=nodeState,senderClusterheadId=nodeClusterheadId))
  File "/Users/vimanyuaggarwal/anaconda/envs/env-iNet/lib/python2.7/site-packages/grpc/_channel.py", line 492, in __call__
    return _end_unary_response_blocking(state, call, False, deadline)
  File "/Users/vimanyuaggarwal/anaconda/envs/env-iNet/lib/python2.7/site-packages/grpc/_channel.py", line 440, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
_Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.UNAVAILABLE, Connect Failed)>

2018-05-04 18:58:47,349 - client - ERROR - Node:11 - <_Rendezvous of RPC that terminated with (StatusCode.UNAVAILABLE, Connect Failed)>
2018-05-04 18:58:47,350 - client - ERROR - Traceback (most recent call last):
  File "/Users/vimanyuaggarwal/Python Projects/cmpe294A/code/phase1/client.py", line 415, in sendHello
    senderState=nodeState,senderClusterheadId=nodeClusterheadId))
  File "/Users/vimanyuaggarwal/anaconda/envs/env-iNet/lib/python2.7/site-packages/grpc/_channel.py", line 492, in __call__
    return _end_unary_response_blocking(state, call, False, deadline)
  File "/Users/vimanyuaggarwal/anaconda/envs/env-iNet/lib/python2.7/site-packages/grpc/_channel.py", line 440, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
_Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.UNAVAILABLE, Connect Failed)>

